# Do not use this file in production.
name: omnibox-backend-dev

services:
  app:
    image: node:22
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    working_dir: /app
    volumes:
      - ${PWD}:/app
      - ${PWD}/.tmp/node_modules:/app/node_modules
    command: ["sh", "-c", "npm install && npm run start:debug"]
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17-alpine
    ports:
      - '${DB_PORT:-5432}:${DB_PORT:-5432}'
    environment:
      - POSTGRES_DB=${DB_DATABASE:-omnibox}
      - POSTGRES_USER=${DB_USERNAME:-omnibox}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-omnibox}
      - POSTGRES_PORT=${DB_PORT:-5432}
    volumes:
      - ${PWD}/.tmp/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE:-omnibox}", "-U", "${DB_USERNAME:-omnibox}", "-p", "${DB_PORT:-5432}"]
      interval: 5s
      timeout: 3s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '8888:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - ${PWD}/.tmp/pgadmin:/var/lib/pgadmin
