name: omnibox-backend-dev

services:
  app:
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:17-alpine
    ports:
      - '${DB_PORT:-5432}:${DB_PORT:-5432}'
    environment:
      - POSTGRES_DB=${DB_DATABASE:-omnibox}
      - POSTGRES_USER=${DB_USERNAME:-omnibox}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-omnibox}
      - POSTGRES_PORT=${DB_PORT:-5432}
    volumes:
      - ${PWD}/.tmp/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE:-omnibox}", "-U", "${DB_USERNAME:-omnibox}", "-p", "${DB_PORT:-5432}"]
      interval: 5s
      timeout: 3s
      retries: 5
