# docker compose -f compose.yaml -f dev.yaml up
services:
  app:
    image: node:22
    working_dir: /app
    volumes:
      - ${PWD}:/app
      - ${PWD}/.tmp/node_modules:/app/node_modules
    command: ["sh", "-c", "npm install && npm run start:debug"]

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '8888:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - ${PWD}/.tmp/pgadmin:/var/lib/pgadmin
