onlyBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'
  - '@swc/core'
  - bcrypt
  - cpu-features
  - protobufjs
  - ssh2

patchedDependencies:
  nest-wechatpay-node-v3: patches/nest-wechatpay-node-v3.patch
  wechatpay-node-v3: patches/wechatpay-node-v3.patch
