[tool.poetry]
name = "omnibox-backend"
version = "0.1.0"
description = ""
authors = ["Lucien Shui <lucien@lucien.ink>"]
license = "Apache License 2.0"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
pydantic = "^2.10.3"
fastapi = "^0.115.6"
uvicorn = "^0.34.0"
shortuuid = "^1.0.13"
sqlalchemy = {extras = ["asyncio"], version = "^2.0.36"}
asyncpg = "^0.30.0"
bcrypt = "^4.2.1"
httpx = "^0.28.1"


[tool.poetry.group.test.dependencies]
testcontainers = "^4.9.0"
pytest = "^8.3.4"
pytest-asyncio = "^0.25.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
