version: '3.8'

services:
  app:
    build: .
    container_name: app
    ports:
      - '3000:9005'
    depends_on:
      - db
      # - redis

  db:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  # redis:
  #   image: redis:7-alpine
  #   command: redis-server --save 60 1 --loglevel warning
  #   volumes:
  #     - redis_data:/data

volumes:
  pgadmin-data:
  postgres_data:
  # redis_data:
